"""users update

Revision ID: 9a087055ecad
Revises: 2c72d72c4afa
Create Date: 2018-03-22 11:11:03.231754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a087055ecad'
down_revision = '2c72d72c4afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wmsi_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wmsi_user')
    # ### end Alembic commands ###
