"""datastory table

Revision ID: 442b7d9e46bf
Revises: 9a087055ecad
Create Date: 2018-03-30 09:53:20.311594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442b7d9e46bf'
down_revision = '9a087055ecad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_story_timestamp'), 'data_story', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('data_story', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_story')
    op.drop_index(op.f('ix_data_story_timestamp'), table_name='data_story')
    op.drop_table('data_story')
    # ### end Alembic commands ###
