"""added archive field

Revision ID: c250914d23de
Revises: 894e9c93fab0
Create Date: 2018-12-10 14:28:53.015053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c250914d23de'
down_revision = '894e9c93fab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_story', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_story', 'archived')
    # ### end Alembic commands ###
